(() => {
  const $ = (selector) => document.querySelector(selector);
  const state = {category:'all', query:'', cart:[]};
  const yen = (amount) => `¥${Number(amount || 0).toLocaleString('ja-JP')}`;
  const catalog = () => (globalThis.KISARAGI_CANONICAL_CATALOG || []).filter((item) => item.status !== 'PRICE_CONFLICT');
  const key = 'kisaragi-shop-demo-cart-v1';
  const imageFor = (item) => item.images?.[0]?.file_path || item.image?.file_path || null;
  const categoryLabels = {CIGARETTES:'紙巻きたばこ',HEATED_TOBACCO_STICKS:'加熱式たばこスティック',HEATED_TOBACCO_DEVICES:'加熱式たばこデバイス'};
  const readableCategory = (item) => categoryLabels[item.category] || item.category?.replaceAll('_',' ') || '商品';
  function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');window.setTimeout(()=>el.classList.remove('show'),2200)}
  function save(){localStorage.setItem(key,JSON.stringify(state.cart.map((item)=>item.id)))}
  function restore(){try{const ids=JSON.parse(localStorage.getItem(key)||'[]');state.cart=ids.map((id)=>catalog().find((item)=>item.id===id)).filter(Boolean)}catch{state.cart=[]}}
  function matching(){const query=state.query.trim().toLocaleLowerCase('ja');return catalog().filter((item)=>{const text=[item.brand,item.product_name_ja,item.sku,item.product_code].filter(Boolean).join(' ').toLocaleLowerCase('ja');return (state.category==='all'||item.category===state.category)&&(!query||text.includes(query))})}
  function renderFilters(){const categories=[...new Set(catalog().map((item)=>item.category).filter(Boolean))];const host=$('#categoryFilters');host.innerHTML='';[['all','すべて'],...categories.map((category)=>[category,readableCategory({category})])].forEach(([value,label])=>{const button=document.createElement('button');button.type='button';button.textContent=label;button.setAttribute('aria-pressed',String(value===state.category));button.addEventListener('click',()=>{state.category=value;renderFilters();renderProducts()});host.append(button)})}
  function renderProducts(){const items=matching();const host=$('#productGrid');host.innerHTML='';$('#resultCount').textContent=`${items.length} 件を表示`;
    items.forEach((item)=>{const card=document.createElement('article');card.className='product-card';const image=imageFor(item);const name=item.product_name_ja||item.name||'商品名確認中';const amount=item.price_jpy||item.price||0;const canChoose=Boolean(image)&&Boolean(amount)&&item.status!=='IDENTITY_PENDING';card.innerHTML=`${image?`<img class="product-image" src="${image}" alt="${name}">`:'<div class="product-empty">画像確認中</div>'}<div class="product-copy"><p class="product-meta">${readableCategory(item)}</p><h3 class="product-name">${name}</h3><p class="product-code">${item.product_code||item.sku||'品番確認中'}</p><div class="product-bottom"><div class="price">${amount?yen(amount):'価格確認中'}<small>${canChoose?'参考価格':'選択対象外'}</small></div><button class="add-button" type="button" ${canChoose?'':'disabled'}>${canChoose?'選択する':'確認待ち'}</button></div></div>`;if(canChoose)card.querySelector('button').addEventListener('click',()=>add(item));host.append(card)});
    if(!items.length)host.innerHTML='<p class="product-empty">該当する商品がありません。</p>';
  }
  function add(item){if(!state.cart.some((entry)=>entry.id===item.id)){state.cart.push(item);save();renderCart();toast('選択リストに追加しました')}else{toast('すでに選択されています')}}
  function renderCart(){const host=$('#cartItems');host.innerHTML='';$('#cartCount').textContent=state.cart.length;const total=state.cart.reduce((sum,item)=>sum+Number(item.price_jpy||item.price||0),0);$('#cartTotal').textContent=yen(total);if(!state.cart.length){host.innerHTML='<p class="panel-note">まだ商品は選択されていません。</p>';return}state.cart.forEach((item)=>{const line=document.createElement('div');line.className='cart-line';line.innerHTML=`<div><p><strong>${item.product_name_ja||item.name}</strong></p><p>${item.product_code||item.sku||''}</p><button class="remove" type="button">削除</button></div><strong>${yen(item.price_jpy||item.price)}</strong>`;line.querySelector('.remove').addEventListener('click',()=>{state.cart=state.cart.filter((entry)=>entry.id!==item.id);save();renderCart()});host.append(line)})}
  function openCart(){const panel=$('#cartPanel');panel.classList.add('open');panel.setAttribute('aria-hidden','false');$('#backdrop').hidden=false;$('#closeCart').focus()}
  function closeCart(){const panel=$('#cartPanel');panel.classList.remove('open');panel.setAttribute('aria-hidden','true');$('#backdrop').hidden=true;$('#openCart').focus()}
  function openReview(){if(!state.cart.length){toast('商品を選択してから確認してください');return}$('#reviewSummary').innerHTML=state.cart.map((item)=>`<p><strong>${item.product_name_ja||item.name}</strong><br>${item.product_code||item.sku||''} - ${yen(item.price_jpy||item.price)}</p>`).join('')+`<p><strong>参考合計 ${$('#cartTotal').textContent}</strong></p>`;$('#reviewModal').setAttribute('aria-hidden','false');closeCart();$('.close-review').focus()}
  function closeReview(){$('#reviewModal').setAttribute('aria-hidden','true');$('#openCart').focus()}
  let releaseGateLock=null;
  function lockAge(){const gate=$('#ageGate');const background=[...document.body.children].filter((element)=>element!==gate&&element.tagName!=='SCRIPT');background.forEach((element)=>{element.dataset.agePreviousAria=element.getAttribute('aria-hidden')||'';element.setAttribute('aria-hidden','true');element.setAttribute('inert','')});document.body.style.overflow='hidden';const focusable=()=>[...gate.querySelectorAll('button,[href]')].filter((element)=>!element.hidden);const trap=(event)=>{if(event.key!=='Tab')return;const items=focusable();if(!items.length)return;const first=items[0];const last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};gate.addEventListener('keydown',trap);window.setTimeout(()=>focusable()[0]?.focus(),0);releaseGateLock=()=>{gate.removeEventListener('keydown',trap);background.forEach((element)=>{const previous=element.dataset.agePreviousAria;if(previous)element.setAttribute('aria-hidden',previous);else element.removeAttribute('aria-hidden');element.removeAttribute('inert');delete element.dataset.agePreviousAria});document.body.style.overflow='';releaseGateLock=null}}
  function releaseAge(){releaseGateLock?.();localStorage.setItem('kisaragi-shop-age-verified','true');$('#ageGate').hidden=true}
  function init(){restore();renderFilters();renderProducts();renderCart();$('#searchInput').addEventListener('input',(event)=>{state.query=event.target.value;renderProducts()});$('#openCart').addEventListener('click',openCart);$('#closeCart').addEventListener('click',closeCart);$('#backdrop').addEventListener('click',closeCart);$('#openReview').addEventListener('click',openReview);$('.close-review').addEventListener('click',closeReview);$('#closeReview').addEventListener('click',closeReview);$('#enterSite').addEventListener('click',releaseAge);if(localStorage.getItem('kisaragi-shop-age-verified')==='true')releaseAge();else lockAge()}
  window.addEventListener('DOMContentLoaded',init);
})();
